# -*- coding: utf-8 -*-
# """Another copy of 77%_hw2_sshultan_1.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/11SfbzOtIrEvyjc6KgGpcl8C9MN8DLKbf
# """

# from google.colab import drive
# drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import csr_matrix
from collections import Counter
from sklearn.feature_selection import SelectKBest, chi2, VarianceThreshold
from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from imblearn.pipeline import make_pipeline
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTEENN
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.base import clone
from sklearn.model_selection import GridSearchCV, StratifiedKFold, learning_curve
from sklearn.naive_bayes import MultinomialNB


# Function to load data
def load_sparse_data(filename):
    data = []
    row_indices = []
    col_indices = []
    labels = []
    with open(filename, 'r') as file:
        for i, line in enumerate(file):
            parts = line.strip().split()
            labels.append(int(parts[0]))
            for part in parts[1:]:
                feature_idx = int(part)
                row_indices.append(i)
                col_indices.append(feature_idx)
                data.append(1)
    X = csr_matrix((data, (row_indices, col_indices)))
    return X, np.array(labels)

# Load training and test data
X_train, y_train = load_sparse_data('/scratch/mbiswas2/CS 580/Assignment 02/train.txt')
X_test, _ = load_sparse_data('/scratch/mbiswas2/CS 580/Assignment 02/test.txt')

# Remove low variance features
selector = VarianceThreshold(threshold=0.01)
X_train_selected = selector.fit_transform(X_train)
X_test_selected = selector.transform(X_test)

# Define a list of classifiers to compare
classifiers = {
    'Naive Bayes Bernoulli': BernoulliNB(),
    'Naive Bayes Multinomial': MultinomialNB(),
    'Decision Tree': DecisionTreeClassifier(class_weight='balanced')
}

# Define sampling strategies to compare
samplings = {
    'SMOTE': SMOTE(random_state=42),
    'SMOTEENN': SMOTEENN()
}

# Store the best model, its name, sampling strategy, and score
best_model = None
best_name = None
best_sampling = None
best_score = -np.inf

# Loop through classifiers and samplings
for sampling_name, sampling in samplings.items():
    for name, classifier in classifiers.items():
        pipeline = make_pipeline(
            sampling,
            SelectKBest(chi2),
            clone(classifier)
        )
        for i in range(1,15000, 5):
            param_grid = {
                'selectkbest__k': [i],
                'decisiontreeclassifier__max_depth': [None, 10, 20],
                'decisiontreeclassifier__min_samples_split': [2, 10],
                'decisiontreeclassifier__min_samples_leaf': [1, 5]
            } if name == 'Decision Tree' else {}

            grid_search = GridSearchCV(pipeline, param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
            grid_search.fit(X_train_selected, y_train)
            # print(f"{sampling_name} with {name} - Best parameters: {grid_search.best_params_}")
            # print(f"{sampling_name} with {name} - Best cross-validation F1 score: {grid_search.best_score_}")

            # Update the best model if the current model is better
            if grid_search.best_score_ > best_score:
                best_model = grid_search.best_estimator_
                best_name = name
                best_sampling = sampling_name
                best_score = grid_search.best_score_

# Output the best overall model
print(f"Best Model: {best_name} with F1 score: {best_score}")

# Use the best model to predict on test data
y_test_pred = best_model.predict(X_test_selected)

# Save the predictions
np.savetxt('result_nb_chi_updated.dat', y_test_pred, fmt='%d')
print("Test predictions saved successfully.")

# Plot class distribution for test predictions
test_class_counts = Counter(y_test_pred)
plt.bar(test_class_counts.keys(), test_class_counts.values(), color=['blue', 'red'])
plt.title('Test Predictions Class Distribution')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks([0, 1])
plt.show()

# Plot learning curve
def plot_learning_curve(estimator, title, X, y, cv=None, n_jobs=None, train_sizes=np.linspace(.1, 1.0, 5)):
    plt.figure()
    plt.title(title)
    plt.xlabel("Training examples")
    plt.ylabel("Score")
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes, scoring="f1_weighted")
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    plt.grid()

    plt.fill_between(train_sizes, train_scores_mean - train_scores_std,
                     train_scores_mean + train_scores_std, color="gray", alpha=0.1)
    plt.fill_between(train_sizes, test_scores_mean - test_scores_std,
                     test_scores_mean + test_scores_std, color="gray", alpha=0.1)
    plt.plot(train_sizes, train_scores_mean, 'o-', color="r",
             label="Training score")
    plt.plot(train_sizes, test_scores_mean, 'o-', color="g",
             label="Cross-validation score")

    plt.legend(loc="best")
    return plt

# Display learning curve for the best classifier
plot_learning_curve(best_model, f"Learning Curve ({best_name} using {best_sampling})", X_train_selected, y_train, cv=StratifiedKFold(n_splits=5), n_jobs=-1).show()